### ISSUE TITLE
[Umbrella] Externalise UI kit

### ISSUE THREAD

**Issue by Dergash** [tesler-platform/tesler-ui#18]
At the moment tesler-ui is hardcoded to work with [Ant Design UI components](https://ant.design/) while there is a strong demand from clients to use our platform with their own internal UI kits.

We should find a way to provide all our features independently from UI controls. As proof of concept, we should try to implement our Table Widget with a different UI kit.

**PoC**
- [ ] Figure out our `<TableWidget />` current functionality in terms of tests statements
- [ ] Cover our `<TableWidget />` with unit tests
- [ ] Replace Ant Design Table with [Material UI Table](https://material-ui.com/components/tables/) while preserving our overall Widget functionality to figure out what contract we should've being providing
- [ ] Replace Ant Design Input with [Material UI TextField](https://material-ui.com/components/text-fields/) while preserving our overall Field functionality
